### PR TITLE
Jenkinsfile modifications

### PR DESCRIPTION
**Pull request by zroubalik**

### CODE REVIEW

**Comment by elmiko** [comment]
the changes lgtm, but it looks like we are having issues with `oc cluster up` running, is this something on our end or travis?

**Comment by zroubalik** [comment]
it looks like a problem on travis side, for sure not caused by this change :)

**Comment by zroubalik** [comment]
This problem is caused by the testsuite, because after it's completion it tries to switch back to original Openshift project (the one that the test user was using before running the testsuite). But if there are multiple runs in the same time on the same Openshift instance, the "original" project could be deleted in the meantime. I'm fixing this problem in this PR, but the CI is using Jenkinsfile from master as a definition for the actual build , so the problem will be fixed after mergin this PR :)

**Comment by elmiko** [comment]
makes perfect sense, thanks!

**Pull request merged**
