### PR TITLE
Return an error on scale when cluster does not exist

### PR DESCRIPTION
**Pull request by tmckayus**
Use the presence of the dcs as the indicator that
a cluster exists.

### CODE REVIEW

**Comment by tmckayus** [comment]
This is a fix for https://github.com/radanalyticsio/oshinko-cli/issues/5

**Comment by tmckayus** [comment]
WIP, there may be additional tweaks to add to this PR

**Comment by sub-mod** [comment]
is this PR valid anymore @tmckayus  ?

**Comment by tmckayus** [comment]
Closing this PR, it's superseded by switching the CLI to use oshinko-core

**Pull request closed without merging**
