### PR TITLE
Merge the oshinko-rest repo into oshinko-cli

### PR DESCRIPTION
**Pull request by tmckayus**
This will allow -rest and -cli to use the same ./core and make it much easier to keep them in sync.

### CODE REVIEW

**Comment by elmiko** [comment]
this mostly works for me, it builds, the unit tests can run, but the client tests are broken. imo, we should probably merge and fix the client tests in a followup.

**Comment by elmiko** [comment]
after some investigation, i can see the problem with the client tests. won't be tough to fix.

**Comment by tmckayus** [comment]
Ack on clients.  There are some missing commits.  I'll get those in after.  Merging in -rest into a subdirectory and preserving history has been a bit thorny.

**Comment by elmiko** [comment]
understood, i'll re-check the tests once we get all the commits in place. but, i'm pretty sure we'll need to adjust the client test script.

**Pull request merged**
