### PR TITLE
Cluster create will now also expose the Spark UI by default

### PR DESCRIPTION
**Pull request by crobby**
The cli supports an optional exposeui flag which defaults to true.

### CODE REVIEW

**Comment by crobby** [comment]
Not quite ready yet.  I still need to add the rest portion.

**Comment by sub-mod** [comment]
@crobby kindly rebase again, I like to see the travis integration test run for this.

**Comment by elmiko** [comment]
tested this locally against master of openshift origin, works for me. agreed with subin about the tests.

**Comment by crobby** [comment]
The tests did run (I had a few more changes after his comment....which was aimed at seeing a real PR have the new tests run)

**Pull request merged**
