### PR TITLE
Add ephemeral commands to main binary

### PR DESCRIPTION
**Pull request by tmckayus**

### CODE REVIEW

**Comment by tmckayus** [comment]
hmm, the "get" against the openshift binary (used by hack/test-cmd.sh) sometimes fails for no good reason.  It reports that there is no cluster, when a cluster has been created and clearly exists.  I think this is a false negative.  One option is to run the travis tests against oc cluster up using run.sh ...

**Comment by elmiko** [comment]
i am testing this now, but is there a document that lists all the ephemeral commands?

i see the tests that are added, just curious if i missed it in the doc update.

**Comment by tmckayus** [comment]
Note, I left out configmap tests, on the way ...

**Comment by elmiko** [comment]
i tested out the commands manually using the following cluster:

```
$ oc version
oc v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
features: Basic-Auth

Server https://shift.opb.studios:8443
openshift v3.6.0-rc.0+98b3d56
kubernetes v1.6.1+5115d708d7
```

and 
```
$ ./oshinko version
oshinko 2017-6-0-9bcb3b7f
```

all the commands worked as predicted, but i noticed a couple sticking points.

1. getting a cluster using the `--app`, i expected that i could use the deployment config name to get the cluster but it looks like it wants the actual deployment. maybe the docs should be clearer, i assumed deployment config as those names are pretty stable.

2. deleting a cluster produces some odd error side effects, for example:
```
$ ./oshinko create_eph foo-bar
shared cluster "foo-bar" created 

$ ./oshinko get_eph

cluster-y0jsk4   1       spark://cluster-y0jsk4:7077     http://cluster-y0jsk4-ui:8080           cluster-y0jsk4-ui-route-pi.shift.opb.studios    Running          sparkpi-2
foo-bar          1       spark://foo-bar:7077            http://foo-bar-ui:8080                  foo-bar-ui-route-pi.shift.opb.studios   Running          <shared>

$ ./oshinko delete_eph foo-bar
unable to delete replication controller foo-bar-m-1 (replicationcontrollers "foo-bar-m-1" not found), unable to delete replication controller foo-bar-w-1 (replicationcontrollers "foo-bar-w-1" not found)
cluster "foo-bar" deleted 

$ ./oshinko get_eph

cluster-y0jsk4   1       spark://cluster-y0jsk4:7077     http://cluster-y0jsk4-ui:8080           cluster-y0jsk4-ui-route-pi.shift.opb.studios    Running          sparkpi-2
```

otherwise the code lgtm

**Comment by tmckayus** [comment]
Fixed the help for app values. The extra info output can be fixed in another PR (suppress unless a verbose flag is set on the delete command, or the command actually fails)

**Comment by elmiko** [comment]
tested the latest change, lgtm

**Pull request merged**
